-- Neon PostgreSQL Schema
-- Database: neondb

-- Drop tables if they exist (in correct order due to foreign keys)
DROP TABLE IF EXISTS APORTES CASCADE;
DROP TABLE IF EXISTS BOLSILLOS CASCADE;
DROP TABLE IF EXISTS ITEMS_PRESUPUESTO CASCADE;
DROP TABLE IF EXISTS PRESUPUESTOS CASCADE;
DROP TABLE IF EXISTS MENSAJES_CHAT CASCADE;
DROP TABLE IF EXISTS PARTICIPANTES_ENCUENTRO CASCADE;
DROP TABLE IF EXISTS ENCUENTROS CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;

-- Create USUARIOS table
CREATE TABLE USUARIOS (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_ACCESO TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT TRUE
);

-- Create ENCUENTROS table
CREATE TABLE ENCUENTROS (
    ID_ENCUENTRO SERIAL PRIMARY KEY,
    NOMBRE_ENCUENTRO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    UBICACION VARCHAR(255),
    PRESUPUESTO_TOTAL DECIMAL(12,2) DEFAULT 0,
    ID_CREADOR INTEGER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(50) DEFAULT 'PLANIFICACION',
    CONSTRAINT FK_ENCUENTRO_CREADOR FOREIGN KEY (ID_CREADOR) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CHK_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO)
);

-- Create PARTICIPANTES_ENCUENTRO table
CREATE TABLE PARTICIPANTES_ENCUENTRO (
    ID_PARTICIPANTE SERIAL PRIMARY KEY,
    ID_ENCUENTRO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    ROL VARCHAR(50) DEFAULT 'PARTICIPANTE',
    CONFIRMADO BOOLEAN DEFAULT FALSE,
    FECHA_CONFIRMACION TIMESTAMP,
    CONSTRAINT FK_PARTICIPANTE_ENCUENTRO FOREIGN KEY (ID_ENCUENTRO) 
        REFERENCES ENCUENTROS(ID_ENCUENTRO) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPANTE_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT UQ_PARTICIPANTE UNIQUE (ID_ENCUENTRO, ID_USUARIO)
);

-- Create MENSAJES_CHAT table
CREATE TABLE MENSAJES_CHAT (
    ID_MENSAJE SERIAL PRIMARY KEY,
    ID_ENCUENTRO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    CONTENIDO TEXT NOT NULL,
    FECHA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EDITADO BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_MENSAJE_ENCUENTRO FOREIGN KEY (ID_ENCUENTRO) 
        REFERENCES ENCUENTROS(ID_ENCUENTRO) ON DELETE CASCADE,
    CONSTRAINT FK_MENSAJE_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

-- Create PRESUPUESTOS table
CREATE TABLE PRESUPUESTOS (
    ID_PRESUPUESTO SERIAL PRIMARY KEY,
    ID_ENCUENTRO INTEGER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    PRESUPUESTO_ASIGNADO DECIMAL(12,2) NOT NULL,
    GASTO_ACTUAL DECIMAL(12,2) DEFAULT 0,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRESUPUESTO_ENCUENTRO FOREIGN KEY (ID_ENCUENTRO) 
        REFERENCES ENCUENTROS(ID_ENCUENTRO) ON DELETE CASCADE,
    CONSTRAINT CHK_PRESUPUESTO_POSITIVO CHECK (PRESUPUESTO_ASIGNADO >= 0),
    CONSTRAINT CHK_GASTO_POSITIVO CHECK (GASTO_ACTUAL >= 0)
);

-- Create ITEMS_PRESUPUESTO table
CREATE TABLE ITEMS_PRESUPUESTO (
    ID_ITEM SERIAL PRIMARY KEY,
    ID_PRESUPUESTO INTEGER NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    MONTO DECIMAL(12,2) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_REGISTRADO_POR INTEGER NOT NULL,
    CONSTRAINT FK_ITEM_PRESUPUESTO FOREIGN KEY (ID_PRESUPUESTO) 
        REFERENCES PRESUPUESTOS(ID_PRESUPUESTO) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_USUARIO FOREIGN KEY (ID_REGISTRADO_POR) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CHK_MONTO_POSITIVO CHECK (MONTO > 0)
);

-- Create BOLSILLOS table
CREATE TABLE BOLSILLOS (
    ID_BOLSILLO SERIAL PRIMARY KEY,
    ID_ENCUENTRO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    MONTO_APORTADO DECIMAL(12,2) DEFAULT 0,
    SALDO_ACTUAL DECIMAL(12,2) DEFAULT 0,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BOLSILLO_ENCUENTRO FOREIGN KEY (ID_ENCUENTRO) 
        REFERENCES ENCUENTROS(ID_ENCUENTRO) ON DELETE CASCADE,
    CONSTRAINT FK_BOLSILLO_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT UQ_BOLSILLO UNIQUE (ID_ENCUENTRO, ID_USUARIO),
    CONSTRAINT CHK_MONTO_APORTADO CHECK (MONTO_APORTADO >= 0),
    CONSTRAINT CHK_SALDO CHECK (SALDO_ACTUAL >= 0)
);

-- Create APORTES table
CREATE TABLE APORTES (
    ID_APORTE SERIAL PRIMARY KEY,
    ID_BOLSILLO INTEGER NOT NULL,
    MONTO DECIMAL(12,2) NOT NULL,
    CONCEPTO VARCHAR(255),
    FECHA_APORTE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO VARCHAR(50) DEFAULT 'INGRESO',
    CONSTRAINT FK_APORTE_BOLSILLO FOREIGN KEY (ID_BOLSILLO) 
        REFERENCES BOLSILLOS(ID_BOLSILLO) ON DELETE CASCADE,
    CONSTRAINT CHK_APORTE_MONTO CHECK (MONTO > 0)
);

-- Create indexes for better performance
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_ENCUENTROS_CREADOR ON ENCUENTROS(ID_CREADOR);
CREATE INDEX IDX_ENCUENTROS_ESTADO ON ENCUENTROS(ESTADO);
CREATE INDEX IDX_PARTICIPANTES_ENCUENTRO ON PARTICIPANTES_ENCUENTRO(ID_ENCUENTRO);
CREATE INDEX IDX_PARTICIPANTES_USUARIO ON PARTICIPANTES_ENCUENTRO(ID_USUARIO);
CREATE INDEX IDX_MENSAJES_ENCUENTRO ON MENSAJES_CHAT(ID_ENCUENTRO);
CREATE INDEX IDX_MENSAJES_FECHA ON MENSAJES_CHAT(FECHA_ENVIO);
CREATE INDEX IDX_PRESUPUESTOS_ENCUENTRO ON PRESUPUESTOS(ID_ENCUENTRO);
CREATE INDEX IDX_ITEMS_PRESUPUESTO ON ITEMS_PRESUPUESTO(ID_PRESUPUESTO);
CREATE INDEX IDX_BOLSILLOS_ENCUENTRO ON BOLSILLOS(ID_ENCUENTRO);
CREATE INDEX IDX_BOLSILLOS_USUARIO ON BOLSILLOS(ID_USUARIO);
CREATE INDEX IDX_APORTES_BOLSILLO ON APORTES(ID_BOLSILLO);

-- Create views
CREATE OR REPLACE VIEW VW_RESUMEN_ENCUENTROS AS
SELECT 
    e.ID_ENCUENTRO,
    e.NOMBRE_ENCUENTRO,
    e.FECHA_INICIO,
    e.FECHA_FIN,
    e.ESTADO,
    u.NOMBRE || ' ' || u.APELLIDO AS CREADOR,
    COUNT(DISTINCT pe.ID_USUARIO) AS TOTAL_PARTICIPANTES,
    COALESCE(SUM(p.GASTO_ACTUAL), 0) AS GASTO_TOTAL
FROM ENCUENTROS e
JOIN USUARIOS u ON e.ID_CREADOR = u.ID_USUARIO
LEFT JOIN PARTICIPANTES_ENCUENTRO pe ON e.ID_ENCUENTRO = pe.ID_ENCUENTRO
LEFT JOIN PRESUPUESTOS p ON e.ID_ENCUENTRO = p.ID_ENCUENTRO
GROUP BY e.ID_ENCUENTRO, e.NOMBRE_ENCUENTRO, e.FECHA_INICIO, 
         e.FECHA_FIN, e.ESTADO, u.NOMBRE, u.APELLIDO;

CREATE OR REPLACE VIEW VW_SALDOS_BOLSILLOS AS
SELECT 
    b.ID_BOLSILLO,
    e.NOMBRE_ENCUENTRO,
    u.NOMBRE || ' ' || u.APELLIDO AS USUARIO,
    b.MONTO_APORTADO,
    b.SALDO_ACTUAL,
    (b.MONTO_APORTADO - b.SALDO_ACTUAL) AS MONTO_GASTADO
FROM BOLSILLOS b
JOIN ENCUENTROS e ON b.ID_ENCUENTRO = e.ID_ENCUENTRO
JOIN USUARIOS u ON b.ID_USUARIO = u.ID_USUARIO;

-- Create trigger function for updating saldo
CREATE OR REPLACE FUNCTION actualizar_saldo_bolsillo()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.TIPO = 'INGRESO' THEN
            UPDATE BOLSILLOS 
            SET MONTO_APORTADO = MONTO_APORTADO + NEW.MONTO,
                SALDO_ACTUAL = SALDO_ACTUAL + NEW.MONTO
            WHERE ID_BOLSILLO = NEW.ID_BOLSILLO;
        ELSIF NEW.TIPO = 'EGRESO' THEN
            UPDATE BOLSILLOS 
            SET SALDO_ACTUAL = SALDO_ACTUAL - NEW.MONTO
            WHERE ID_BOLSILLO = NEW.ID_BOLSILLO;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
CREATE TRIGGER TRG_ACTUALIZAR_SALDO
AFTER INSERT ON APORTES
FOR EACH ROW
EXECUTE FUNCTION actualizar_saldo_bolsillo();

-- Insert sample data (optional)
-- Uncomment if you want to test with sample data
/*
INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, CONTRASENA) VALUES
('Admin', 'Sistema', 'admin@encuentros.com', '$2b$10$abcdefghijklmnopqrstuv');
*/

COMMENT ON TABLE USUARIOS IS 'Tabla de usuarios del sistema';
COMMENT ON TABLE ENCUENTROS IS 'Tabla de encuentros/eventos';
COMMENT ON TABLE PARTICIPANTES_ENCUENTRO IS 'Relación entre usuarios y encuentros';
COMMENT ON TABLE MENSAJES_CHAT IS 'Mensajes del chat de cada encuentro';
COMMENT ON TABLE PRESUPUESTOS IS 'Categorías de presupuesto por encuentro';
COMMENT ON TABLE ITEMS_PRESUPUESTO IS 'Items individuales de gasto';
COMMENT ON TABLE BOLSILLOS IS 'Bolsillos/cuentas de cada usuario por encuentro';
COMMENT ON TABLE APORTES IS 'Registro de aportes y gastos de los bolsillos';
